spring:
  application:
    name: franchise-management

  data:
    mongodb:
      host: mongodb+srv://juanmadrinan:6ZTBz9vT1KcPMsKE@cluster0.9p8pcf2.mongodb.net/
      database: Cluster0
      password: 6ZTBz9vT1KcPMsKE

server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.accenture: ${LOGGING_LEVEL_COM_ACCENTURE:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always